[package]
name = "drivers"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
embedded-hal = "1.0.0"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
chrono = { version = "0.4", default-features = false }
postcard = { version = "1.1", default-features = false, features = ["alloc", "heapless"] }
heapless = "0.8"
hashbrown = "0.15"

[dev-dependencies]
testing = { path = "../testing" }
