[package]
name = "drivers"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"
shift-register-driver = "0.1.1"
chrono = "0.4.38"

[dev-dependencies]
testing        = { path = "../testing" }
serde = { version = "1.0", features = ["derive"] }
postcard = "1.0"